# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables

name: Build

on: push

jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    # check out the repository, so the workflow can access it
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2.15'
        node-version: ${{ matrix.node-version }}
    
    - name: Run build
      run: |
        composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
        npm ci
        npm run lint --if-present
        npm run compile --if-present

    # env: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1604-README.md
    # mysql start: https://github.com/actions/virtual-environments/issues/739
    - name: Run tests
      run: |
        sudo /etc/init.d/mysql start
        npm run test --if-present
      env:
        WPUNIT_DB_USER: root
        WPUNIT_DB_PASS: root
        WPUNIT_DB_HOST: 127.0.0.1

    - name: Copy built files to release folder
      run: npm run release --if-present

    # https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts
    - name: Archive release folder
      uses: actions/upload-artifact@v1
      with:
        name: release
        path: release
