# https://stackoverflow.com/questions/59518658/how-to-use-github-release-version-number-in-github-action
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#release-event-release
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release
# https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow

name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Download release folder from Build
      uses: actions/download-artifact@v1
      with:
        name: release

    - name: Zip release folder
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./release-${{ github.event.release.tag_name }}.zip ./release

    - name: Upload release to the repository's Releases page
      uses: yakuhzi/action-release@v1
      with:
        file: release-${{ github.event.release.tag_name }}.zip
        changelog: README.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
